# Generated by Django 5.1.3 on 2024-11-22 13:16

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Razón Social')),
                ('phone', models.CharField(default='0000000000', max_length=12, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(default='', max_length=254, null=True, verbose_name='Email de contacto')),
                ('address', models.TextField(default='', null=True, verbose_name='Dirección')),
                ('qr', models.ImageField(blank=True, help_text='Select file to upload', upload_to=gestion.models.upload_form_qr, verbose_name='QR')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
