# Generated by Django 5.1.3 on 2024-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.CharField(default='', max_length=20, verbose_name='PIN'),
        ),
    ]
