# Generated by Django 5.1.3 on 2024-12-11 13:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_date', models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 44, 37, 457802), null=True, verbose_name='Inicio')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 44, 37, 457836), null=True, verbose_name='Fin')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.client', verbose_name='Client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistances', to='gestion.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
