# Generated by Django 5.1.3 on 2024-12-11 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='inside',
            field=models.BooleanField(default=False, verbose_name='Dentro'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 49, 8, 456950), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 49, 8, 456922), null=True, verbose_name='Inicio'),
        ),
    ]
