# Generated by Django 5.1.3 on 2024-12-20 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_assistance_inside_assistance_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AddField(
            model_name='employee',
            name='dni',
            field=models.CharField(default='', max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 11, 52, 32, 130524), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 11, 52, 32, 130498), null=True, verbose_name='Inicio'),
        ),
    ]
