# Generated by Django 5.1.3 on 2024-12-20 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_assistance_options_employee_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Desactivado'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 12, 9, 56, 770862), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 20, 12, 9, 56, 770835), null=True, verbose_name='Inicio'),
        ),
    ]
