# Generated by Django 5.1.3 on 2025-01-02 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_client_inactive_alter_assistance_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 9, 39, 3, 542427), null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='ini_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 9, 39, 3, 542378), null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
